# Generated by Django 3.2.9 on 2021-12-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktd',
            name='Email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
