# Generated by Django 3.2.9 on 2021-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt', '0002_ktd_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ktd',
            old_name='pswd',
            new_name='psw1',
        ),
        migrations.AddField(
            model_name='ktd',
            name='psw2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
