# Generated by Django 3.2.9 on 2021-12-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt', '0003_auto_20211214_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
